### ISSUE TITLE
Domain VPN routing Beta 2.1

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#7] opened 2023-09-29 16:24 UTC
Hi,
Here are some observations on the 2.1 beta:
- after the update the cursor just hangs - no return to menu or exit. Ctrl+x only.
- after creating the policy, I manually add the domains to the /jffs/configs domainlist. It then upon query adds the IPs to the domaintoip file. However the *ipv4.ipset file only has the top line; it doesn't get populated at all.
- `ip rule` command looks like (the relevant part):
`7000:   from all fwmark 0x2100/0x2100 unreachable`
`7000:   from all fwmark 0x2100/0x2100 lookup wgc2`
`9000:   from all fwmark 0x7100/0x7100 unreachable`
`9000:   from all fwmark 0x7100/0x7100 lookup wgc4`
-and `iptables -nvL PREROUTING -t mangle --line`:
`7        0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DomainVPNRouting-<ipset1>-ipv4 dst MARK or 0x7100`
`8      136  7320 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DomainVPNRouting-<ipset2>-ipv4 dst MARK or 0x2100`
`9    19417 1185K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DomainVPNRouting-<ipset3>-ipv4 dst MARK or 0x2100`

Thoughts?

**Comment by Ranger802004** [comment] 2023-09-30 23:37
Can you run update and see if you have the most up to date code installed? I had to republish this version due to a minor issue involving the ipv4 sets not creating.  Once you verify you are on the latest code delete all of the .ipset files under /jffs/configs/domain_vpn_routing directory and reboot to clear out the invalid unreachable rules that were created.  Also please collect system logs and forward those if possible, then on verbose logging for a policy to help diagnose, thank you.

**Comment by dorner365** [comment] 2023-10-01 02:18
Congratulations for filling the ipset selective routing gap. The previous version worked, but unsustainable for large ipsets.
Much better approach now.

I uninstalled the script altogether and re-installed after a reboot.
This time around after installing it and adding the domains it works - 3 ipsets, 2 interfaces (one ovpn and one wg) as above.
Upgrading to the latest dev version still has the issue in the first bullet above.

After another reboot, one of the interfaces was 'unreachable' (as above). I manually deleted it and everything started working. The question is why did the 'unreachable' remain there on one interface  and firstly why do you need it?

'ip rule' priority wise I don't see  why the vpn interfaces should be higher than wan0. Typically, wan0 was after local and then the rest of them (whether ovpn should be higher than wg as currently implemented for IP routing does not concern me :)).

And finally, could you check for the IPv6 existence and proceed accordingly if not configured?

Thank you.

**Comment by Ranger802004** [comment] 2023-10-01 03:12
What do the route tables look like for your VPN interfaces? The unreachable rules by design are to block traffic that don't have a valid route path via your VPN, for example if you have a VPN that doesn't support IPv6, it will add the IPv6 addresses to the IPv6 upset and create an unreachable rule to prevent leakage via IPv6 routing through the default route. If your VPN interfaces are missing a default route on their proprietary route table then the unreachable rule will be created. The WAN rules exists so if you have all of your traffic routed through VPN you can make and exclusion for domains to still go over WAN.  I will look into your #1 bullet when I am back home Monday.

**Comment by dorner365** [comment] 2023-10-01 11:41
Here is wgc2 client route as example:
ip route show table wgc20.0.0.0/1 dev wgc2 scope linkdefault via <wan0> dev eth010.6.0.0/24 dev tun21 proto kernel scope link src 10.6.0.110.8.0.0/24 dev tun14 proto kernel scope link src 10.8.0.210.13.128.0/24 dev wgc1 proto kernel scope link src 10.13.128.22910.13.130.0/24 dev wgc2 proto kernel scope link src 10.13.130.10110.33.130.0/24 dev wgc5 proto kernel scope link src 10.33.130.310.110.0.0/24 dev wgs1 proto kernel scope link src 10.110.0.110.110.0.2 dev wgs1 scope link10.110.0.3 dev wgs1 scope link<ISP network> via <wan0 GW> dev eth0 metric 1<wan0 network/26> dev eth0 proto kernel scope link src <wan0><wan0 GW> dev eth0 proto kernel scope link127.0.0.0/8 dev lo scope link128.0.0.0/1 dev wgc2 scope link<wgc2 endpoint IP> via <wan0 GW> dev eth0192.168.1.0/24 dev br0 proto kernel scope link src 192.168.1.1<ISP DNS> via <wan0 GW> dev eth0 metric 1
IPv6 is not configured on the router: 


When the unreachable route show up in 'ip rule', routing does not work. Web pages do not open.
As for the 'ip rule' priority, for consistency, I guess, the ipset based selective routing should be in the range with the IP based selective routing as defined through VPN Director. In my case, this what is looks like:
ip rule0:      from all lookup local7000:   from all fwmark 0x2100/0x2100 lookup wgc29000:   from all fwmark 0x7100/0x7100 lookup wgc49990:   from all fwmark 0x8000/0x8000 lookup main10810:  from 192.168.1.198 lookup ovpnc410811:  from all to 192.168.2.0/24 lookup ovpnc411010:  from 192.168.1.237 lookup ovpnc511011:  from 192.168.1.253 lookup ovpnc511012:  from 192.168.1.241 lookup ovpnc511013:  from 192.168.1.242 lookup ovpnc511014:  from 192.168.1.244 lookup ovpnc511015:  from 192.168.1.238 lookup ovpnc511210:  from 192.168.1.230 lookup wgc132766:  from all lookup main32767:  from all lookup default
It still works anyway :).
Thank you


    On Saturday, September 30, 2023 at 11:12:46 p.m. EDT, Ranger802004 ***@***.***> wrote:  
 
 


What do the route tables look like for your VPN interfaces? The unreachable rules by design are to block traffic that don't have a valid route path via your VPN, for example if you have a VPN that doesn't support IPv6, it will add the IPv6 addresses to the IPv6 upset and create an unreachable rule to prevent leakage via IPv6 routing through the default route. If your VPN interfaces are missing a default route on their proprietary route table then the unreachable rule will be created. The WAN rules exists so if you have all of your traffic routed through VPN you can make and exclusion for domains to still go over WAN. I will look into your #1 bullet when I am back home Monday.

**Comment by dorner365** [comment] 2023-10-01 11:50
PM sent with the required info.

**Comment by Ranger802004** [comment] 2023-10-02 13:15
I don't see a message from you?

**Comment by Ranger802004** [comment] 2023-10-02 13:20
Looking at the situation, it looks like it might be a timing issue where when domain_vpn_routing first runs it doesn't see routes in the VPN route tables for WireGuard and creates the unreachable rule and then when it runs again the routes are there and creates the lookup rules but doesn't delete the unreachable.  I will add logic to remove the unreachable rules if they exist when it is creating lookup rules to replace them.  In the mean time just delete the initial unreachable rules at boot up.

**Comment by dorner365** [comment] 2023-10-02 13:30
Yes, that seems to be right. I added some more ipsets and interfaces. Upon reboot the wg interface rules come up as unreachable. Then I run a manual policy query on all and that adds the lookup rules, but does not delete the unreachable ones. Those have to be manually deleted. After that it all works as expected.

Thank you.

**Comment by Ranger802004** [comment] 2023-10-02 14:09
> Yes, that seems to be right. I added some more ipsets and interfaces. Upon reboot the wg interface rules come up as unreachable. Then I run a manual policy query on all and that adds the lookup rules, but does not delete the unreachable ones. Those have to be manually deleted. After that it all works as expected.
> 
> Thank you.

Ok I have this fixed in the next release, I'm looking into the #1 issue you posted by I don't see where it's breaking, it has proper return paths as it should for the menu, update, and killscript functions that are called during the update process.

**Comment by dorner365** [comment] 2023-10-02 14:30
I recently installed the script from page 1 of your thread (v. 2.0.0). I then changed config to allow for dev mode and then downloaded v. 2.1-beta1. After the upgrade, there was no returning to the menu. I had to ctrl+x and then restarted the script.

**Comment by Ranger802004** [comment] 2023-10-02 14:39
> I recently installed the script from page 1 of your thread (v. 2.0.0). I then changed config to allow for dev mode and then downloaded v. 2.1-beta1. After the upgrade, there was no returning to the menu. I had to ctrl+x and then restarted the script.

Ah ok that makes sense, yes the logic in v2.0.0 was very basic for this function and was updated v2.0.1 but when you perform the update the logic uses the current version you are using, in the future you should have proper functionality for this.

v2.0.1:
Enhancements:
- Minor optimizations for performance
- The error log will explicitly state if an IPv6 route already exists when trying to create routes.
- Added NVRAM Checks and Process Priority configuration options to Configuration Menu.
- Major performance optimization for NVRAM Check function.

Fixes:
**- Corrected issue where update process was terminating its own process during update.**
- Corrected issue where IPv6 routes were attempting to be created when IPv6 Service is enabled but IPv6 wasn't available.
- Fixed issue where Dual WAN properties were not being accepted as null in a Single WAN configuration.
- Fixed issue where queried IPv6 addresses don't include complete prefix and cause an error when creating the route for them.

**Comment by Ranger802004** [comment] 2023-10-02 14:46
v2.1.0-beta2 has been published.

**Comment by dorner365** [comment] 2023-10-02 14:58
Make a selection:
6
***Dev Mode is Enabled***
domain_vpn_routing is out of date - Current Version: v2.1.0-beta1 Available Version: v2.1.0-beta2
Do you want to update to the latest beta version? v2.1.0-beta2 ***Enter Y for Yes or N for No***
> y
domain_vpn_routing: Update - domain_vpn_routing has been updated to version: v2.1.0-beta2

...no return to the menu. Pressing enter just moves the cursor to next line. Ctrl+c brings up the updated menu.

**Comment by Ranger802004** [comment] 2023-10-02 16:22
Did you increase the boot delay timer sufficiently to allow time for your VPN tunnels to initialize at boot up? The behavior shows me that your VPN tunnels weren't up and running when Domain VPN Routing executed querypolicy, I personally use 180 seconds.  Yes the IPv6 ipsets are going to be created as a staging placeholder in case you spin up IPv6, when query function runs it will create the ipsets but not perform any add functions to these ipsets for IPv6, this is by design.

**Comment by Ranger802004** [comment] 2023-10-02 17:19
In other news I discovered the issue causing the console to hang when you are performing updates and have implemented the fix.

**Comment by dorner365** [comment] 2023-10-02 17:53
> Did you increase the boot delay timer sufficiently to allow time for your VPN tunnels to initialize at boot up? The behavior shows me that your VPN tunnels weren't up and running when Domain VPN Routing executed querypolicy

Increasing the boot delay locally would be a band-aid. Everyone's "local" means a differing value. Couldn't you (the script that is) check for the interfaces up and run the query at that point? ...because it all works well otherwise :)

**Comment by Ranger802004** [comment] 2023-10-02 17:57
It already does this but at boot up your interfaces are "up" but not initialized necessarily when domain vpn routing is running.  If you go turn off a VPN interface the policy using it will be skipped for example.

**Comment by Ranger802004** [comment] 2023-10-02 20:46
I went ahead and published a beta3 to address the update issue being experienced.

**Comment by dorner365** [comment] 2023-10-02 20:59
That's great.
BTW setting the boot delay timer to 45 sec solves the 'unreachable' issue.

**Comment by Ranger802004** [comment] 2023-10-02 21:02
> That's great. BTW setting the boot delay timer to 45 sec solves the 'unreachable' issue.

Yea the delay timer is to resolve the timing issue, it's out of control on my end other than setting a hard static delay in the delay but my solution is to make it configurable by the end user.

**Closed** 2023-10-04 01:22 UTC
